name: BlockHistory
version: '${project.version}'
main: me.missingdrift.blockhistory.BlockHistory
api-version: 1.19
authors: [ MissingDrift ]
description: ${project.description}
softdepend: [WorldEdit, WorldGuard]
commands:
  lb:
    description: 'blockhistory plugin commands'
    usage: 'Usage: /<command> help'
    aliases: [blockhistory]
permissions:
  blockhistory.*:
    description: Gives access to all blockhistory commands
    children:
      blockhistory.lookup: true
      blockhistory.rollback: true
      blockhistory.clearlog: true
      blockhistory.hide: true
      blockhistory.tp: true
      blockhistory.me: true
      blockhistory.ignoreRestrictions: true
      blockhistory.spawnTools: true
      blockhistory.tools.toolblock: true
      blockhistory.tools.tool: true
  blockhistory.lookup:
    description: 'Grants access to /lb lookup commands and allows defining custom tool queries'
    default: op
  blockhistory.rollback:
    description: 'Allows rollback, redo and writing of logfiles'
    default: op
  blockhistory.clearlog:
    description: 'Allows clearing of the logs via /lb clearlog'
    default: op
  blockhistory.hide:
    description: 'Allows hiding players from logging'
    default: op
  blockhistory.tp:
    description: 'Allows the use of /lb tp'
    default: op
  blockhistory.me:
    description: 'Allows seeing of your own stats with /lb me'
    default: true
  blockhistory.ignoreRestrictions:
    description: 'Allows to ignore the rollback restrictions rollback.maxTime and rollback.maxArea'
    default: op
  blockhistory.spawnTools:
    description: 'Allows lookup tools to be spawned'
    default: true